<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'abstractdeliverystate' => '/AbstractDeliveryState.php',
                'canceleddeliverystate' => '/CanceledDeliveryState.php',
                'collectingdeliverystate' => '/CollectingDeliveryState.php',
                'delivereddeliverystate' => '/DeliveredDeliveryState.php',
                'delivery' => '/Delivery.php',
                'deliverystate' => '/DeliveryState.php',
                'finisheddeliverystate' => '/FinisheddDeliveryState.php',
                'illegalstatetransitionexception' => '/IllegalStateTransitionException.php',
                'inroutedeliverystate' => '/InrouteDeliveryState.php',
                'requesteddeliverystate' => '/RequestedDeliveryState.php',
                'reserveddeliverystate' => '/ReservedDeliveryState.php',
                'returneddeliverystate' => '/ReturnedDeliveryState.php',
                'state' => '/LockedDoorState.php',
                'waitingdeliverystate' => '/WaitingDeliveryState.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
