// Generated by CoffeeScript 1.7.1
(function() {
  define('manageTags', ['lib_fancybox'], function() {
    var catchDom, dom, events, functions, initialize, st, suscribeEvents;
    console.log("manageTags Binded.......");
    st = {
      tag: '.tag-exercise',
      tagMore: '.more-exercise'
    };
    dom = {};
    catchDom = function() {
      dom.tag = $(st.tag);
      dom.tagMore = $(st.tagMore);
    };
    suscribeEvents = function() {
      $("body").on("click", st.tagMore, function() {
        var $this;
        $this = $(this);
        return functions.addExerciseModal($this);
      });
    };
    events = {
      generateModals: function() {}
    };
    functions = {
      addExerciseModal: function(obj) {
        return
      }
    };
    initialize = function() {
      catchDom();
      suscribeEvents();
    };
    return {
      init: initialize()
    };
  });

}).call(this);
